name: Generate Agent Release Notes

on:
  push:
    branches:
      - main

jobs:
  generate-json:
    name: Generate JSON
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: generate and upload
        run: scripts/releaseNotes.mjs --upload
