name: Generate Agent Release Notes

on:
  push:
    branches:
      - master

jobs:
  generate-json:
    name: Generate JSON
    runs-on: ubuntu-latest
    steps:
      - name: generate and upload
        run: scripts/releaseNotes.mjs --upload
